### ISSUE TITLE
[v2.0.1] puma 3.4.0 fails to build on ruby 2.3.1

### ISSUE THREAD

**Issue by noraj** [mcpa-stlouis/hack-the-arch#34]
On last [release](https://github.com/mcpa-stlouis/hack-the-arch/releases/tag/v2.0.1) (v2.0.1) using ruby 2.3.1 puma 3.4.0 fails to build:

```
gem install puma -v '3.4.0'
Building native extensions.  This could take a while...
ERROR:  Error installing puma:
	ERROR: Failed to build gem native extension.

    current directory: /home/shark/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/ext/puma_http11
/home/shark/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20170923-23774-1dauaqn.rb extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
creating Makefile

current directory: /home/shark/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/ext/puma_http11
make "DESTDIR=" clean

current directory: /home/shark/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/ext/puma_http11
make "DESTDIR="
compiling puma_http11.c
compiling mini_ssl.c
mini_ssl.c: In function ‘get_dh1024’:
mini_ssl.c:90:5: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
   dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
     ^~
mini_ssl.c: In function ‘engine_init_server’:
mini_ssl.c:161:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   DH *dh = get_dh1024();
   ^~
mini_ssl.c:165:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   EC_KEY *ecdh = EC_KEY_new_by_curve_name(NID_secp521r1);
   ^~~~~~
mini_ssl.c: In function ‘engine_init_client’:
mini_ssl.c:192:3: warning: ‘DTLSv1_method’ is deprecated [-Wdeprecated-declarations]
   conn->ctx = SSL_CTX_new(DTLSv1_method());
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from mini_ssl.c:15:
/usr/include/openssl/ssl.h:1630:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_method(void)) /* DTLSv1.0 */
 ^
make: *** [Makefile:239: mini_ssl.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/shark/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0 for inspection.
Results logged to /home/shark/.rvm/gems/ruby-2.3.1/extensions/x86_64-linux/2.3.0/puma-3.4.0/gem_make.out
```

**Comment by noraj1337** [comment]
Same probleme with install from the master branch of the git repo using ruby 2.3.3:

```
gem install puma -v '3.4.0'
Building native extensions.  This could take a while...
ERROR:  Error installing puma:
	ERROR: Failed to build gem native extension.

    current directory: /home/shark/.rvm/gems/ruby-2.3.3/gems/puma-3.4.0/ext/puma_http11
/home/shark/.rvm/rubies/ruby-2.3.3/bin/ruby -r ./siteconf20170923-14232-1k17juj.rb extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
creating Makefile

current directory: /home/shark/.rvm/gems/ruby-2.3.3/gems/puma-3.4.0/ext/puma_http11
make "DESTDIR=" clean

current directory: /home/shark/.rvm/gems/ruby-2.3.3/gems/puma-3.4.0/ext/puma_http11
make "DESTDIR="
compiling puma_http11.c
compiling mini_ssl.c
mini_ssl.c: In function ‘get_dh1024’:
mini_ssl.c:90:5: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
   dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
     ^~
mini_ssl.c: In function ‘engine_init_server’:
mini_ssl.c:161:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   DH *dh = get_dh1024();
   ^~
mini_ssl.c:165:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   EC_KEY *ecdh = EC_KEY_new_by_curve_name(NID_secp521r1);
   ^~~~~~
mini_ssl.c: In function ‘engine_init_client’:
mini_ssl.c:192:3: warning: ‘DTLSv1_method’ is deprecated [-Wdeprecated-declarations]
   conn->ctx = SSL_CTX_new(DTLSv1_method());
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from mini_ssl.c:15:
/usr/include/openssl/ssl.h:1630:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_method(void)) /* DTLSv1.0 */
 ^
make: *** [Makefile:239: mini_ssl.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/shark/.rvm/gems/ruby-2.3.3/gems/puma-3.4.0 for inspection.
Results logged to /home/shark/.rvm/gems/ruby-2.3.3/extensions/x86_64-linux/2.3.0/puma-3.4.0/gem_make.out
```

**Comment by noraj1337** [comment]
I think I know where does it come from:

> Ruby versions older than 2.4 require OpenSSL 1.0 but RVM will try to build them with OpenSSL 1.1.

Install the old Ruby 2.3.1 with openssl support (see [stackoverflow](https://stackoverflow.com/questions/15511943/troubles-with-rvm-and-openssl/46378301#46378301) and [archlinux wiki](https://wiki.archlinux.org/index.php/RVM#RVM_uses_wrong_OpenSSL_version)):

```
$ rvm pkg install openssl
$ rvm install 2.3.1 --with-openssl-dir=$HOME/.rvm/usr
```

So either I install ruby normally with `rvm install 2.3.1` but can't install any gem because of a too recent version of openssl or il install ruby with the option ` --with-openssl-dir=$HOME/.rvm/usr` and puma fail.

That's one more reason to update to a more recent version of ruby : https://github.com/mcpa-stlouis/hack-the-arch/issues/33

**Comment by noraj1337** [comment]
So I tried to git clone the repo, reinstall ruby 2.4.0 without `--with-openssl-dir=$HOME/.rvm/usr` (working because ruby 2.4+ works with OpenSSL 1.1 so I'm using system's openssl and not the rvm old package), but I'm stuck because json gem fails to build (see https://github.com/mcpa-stlouis/hack-the-arch/issues/22).

**Comment by noraj1337** [comment]
So I can't build HTA on ArchLinux with ruby 2.3.1, 2.3.3 or 2.4.0 because HTA use too old stuff.  Please consider upgrading to ruby 2.4+, to support a proper openssl 1.1+.

**Comment by cxsper** [comment]
@noraj please, explain how did you succeeded with

```bash
$ rvm install 2.3.1 --with-openssl-dir=$HOME/.rvm/usr
```

for me it ends with

```bash
Error running '__rvm_make -j4',
```

**Comment by noraj** [comment]
This bug doesn't appear anymore with dev branch and the new fix (I tested with ruby 2.5.1).

**Comment by cxsper** [comment]
@noraj as I've mentioned this is not for this package , I am sorry for re-opening, but it's related to this problem with ruby 2.3.1 and puma 3.4.0

**Comment by noraj** [comment]
@cxsper For me it is good, as it was fixed, but yeah you'll need to update your ruby version, this also solve https://github.com/mcpa-stlouis/hack-the-arch/issues/33 and fix some vulnerabilities.

PS : I'm not a member of the project, just an occasional contributor

**Comment by cxsper** [comment]
@noraj there is nothing I am or was trying to do with this project, I just faced the same problem with puma 3.4.0 and ruby 2.3.1, and it was looking like youve managed to fix it somehow.

**Comment by noraj** [comment]
@cxsper I just switched from master branch to dev branch were they are using ruby 2.5 instead of 2.3. But I'm not the dev, I can't tell you what was the fix.

**Comment by paullj1** [comment]
No issues heard after release.  Closing.
